### PR TITLE
V5.15+imans.20211115.v2

### PR DESCRIPTION
**Pull request by DenisSemakin**

### CODE REVIEW

**Comment by DenisSemakin** [comment]
@stefanberger I'd like to send this patches to community as well... but I guess that's too early since IMA-ns is under developmet yet.
But one may consider that "CAP_INTEGRITY_ADMIN" patch is independent of other IMA-ns related patch-set

**Comment by stefanberger** [comment]
Hi Denis.

The patch looks good to me. The community, though, will probably not accept the patch unless they see most/all of the other IMA-ns code that needs this patch...

   Stefan

**Comment by DenisSemakin** [comment]
Yes. I understand that

**Comment by stefanberger** [comment]
Btw, SecurityFS or a version of a filesystem for support of namespaced IMA is one major issue, at least in the architecture we are trying to persue: https://github.com/opencontainers/runc/issues/3288

**Comment by DenisSemakin** [comment]
> Btw, SecurityFS or a version of a filesystem for support of namespaced IMA is one major issue, at least in the architecture we are trying to persue: [opencontainers/runc#3288](https://github.com/opencontainers/runc/issues/3288)

Agree that it's a problem... https://github.com/opencontainers/runc/issues/3288#issuecomment-972956969

**Comment by stefanberger** [comment]
A multi-instance filesystem seems to be an undertaking just by itself considering how other filesystems' code looks and all these different API calls the kernel has...

**Comment by stefanberger** [comment]
I merged your PR now. You find this patch in the most recent branch: https://github.com/stefanberger/linux-ima-namespaces/tree/v5.15%2Bimans.20211119.v2

**Pull request merged**
